config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: %i[new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6, maximum: 50}
  validates :description, presence: true, length: {minimum: 20, maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 6, maximum: 25 }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: {maximum: 105},
            format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
  attr_accessor :password_confirmation

  validate :password_matches_password_confirmation

  def password_matches_password_confirmation
    errors.add :password_confirmation, 'must match your password' if :password.eql? :password_confirmation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  UNPROCESSABLE_ENTITY_STATUS = 422
  OK_STATUS = 200
  NO_CONTENT_STATUS = 205

  ARTICLES_PAGINATION_LIMIT = 5
  USERS_PAGINATION_LIMIT = 5

  ## This makes current_user available also for the views
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:warning] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, expect: %i[show, index]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: ARTICLES_PAGINATION_LIMIT).order('id DESC')
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    set_article
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Article was created successfully'
      redirect_to article_path(@article)
    else
      render action: 'new', status: UNPROCESSABLE_ENTITY_STATUS
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated successfully'
      redirect_to article_path(@article)
    else
      render action: 'edit', status: UNPROCESSABLE_ENTITY_STATUS
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:id, :title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:warning] = 'You cannot edit this article because it is not yours!'
      redirect_to @article
    end

  end
end

app/controllers/pages_controller.rb
# Main pages controller
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in succesfully"
      redirect_to user
    else
      flash.now[:danger] = "Email or password are incorrect"
      render 'new', status: UNPROCESSABLE_ENTITY_STATUS
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:warning] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# Users controller that handles all actions
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[show index edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha blog. You've been succesfully signed up!"
      redirect_to articles_path
    else
      render 'new', status: UNPROCESSABLE_ENTITY_STATUS
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: ARTICLES_PAGINATION_LIMIT).order('id DESC')
  end

  def index
    @users = User.paginate(page: params[:page], per_page: USERS_PAGINATION_LIMIT).order('id DESC')
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your account information was successfully updated'
      redirect_to user_path
    else
      render 'edit', status: UNPROCESSABLE_ENTITY_STATUS
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:warning] = "Account and all associated articles has been succesfully deleted"
    redirect_to articles_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:warning] = 'You can only edit or delete your own account!'
      redirect_to user_path(@user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80, class: '' })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: options[:class])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% if !@articles.nil? && @articles.length > 0 %>
  <table class="fl-table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td>
          <%= button_to "Show", article_path(article), { method: :get, class: 'gc-button gc-icon-button', data: { "article_id": article.id } } %>
        </td>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <td>
            <%= button_to "Delete", article_path(article.id), { method: :delete, class: 'gc-button gc-icon-button' } %>
          </td>
          <td>
            <%= button_to "Edit", edit_article_path(article.id), { method: :get, class: 'gc-button gc-icon-button' } %>
          </td>
        <% end %>
      </tr>
    <% end %>
    <tbody>
    </table>
  <% else %>
  <div class="gc-alert gc-alert-warning">
    <div class="gc-alert-text">
      There's no articles to show
    </div>
  </div>
<%  end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true, class: 'gc-form') do |f| %>
  <p>

    <%= f.label :title, class: 'gc-form-label' %> <br>
    <%= f.text_field :title, class: 'gc-form-input' %>
  </p>
  <p>
    <%= f.label :description, class: 'gc-form-label' %> <br>
    <%= f.text_area :description, class: 'gc-form-textarea' %>
  </p>
  <p>
    <%= f.submit class: 'gc-button gc-form-button' %>
  </p>
<% end %>

<br>

app/views/articles/edit.html.erb
<h1>Update article #<%= @article.id %></h1>

<%= render 'form' %>

<div>
  <%= link_to "Cancel and get back to listing", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="title">
  <h1>Articles</h1>
</div>
<div class="table-wrapper">
  <%= render 'article' %>
</div>
<%= will_paginate @articles %>

<% if logged_in? %>
  <%= button_to "New article", { action: "new"}, { method: :get, class: 'gc-button' } %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<div>
  <%= link_to "Cancel and get back to listing", articles_path %>
</div>

app/views/articles/show.html.erb
<div class="article-card">
  <p class="article-card-id">#<%=@article.id %></p>
  <p class="article-card-title"> <b>Article title:</b> <%= @article.title %></p>
  <p class="article-card-description"> <b>Article description:</b> <%= @article.description %></p>
  <div class="article-card-username"> <div>by <%= link_to @article.user.username, @article.user  %></div> </div>
</div>

<div class="gc-button-group">
  <% if logged_in? && (@article.user == current_user || current_user.admin? ) %>
    <%= button_to "Delete", article_path(@article), { method: :delete, class: 'gc-button', data: { confirm: 'Are you sure?' } } %>
    <%= button_to "Edit", edit_article_path(@article), { method: :get, class: 'gc-button' } %>
  <% end %>
</div>
<div class="gc-button-group">
  <%= link_to "Back to articles", articles_path  %>
</div>

app/views/layouts/_messages.html.erb
<div class="gc-messages-container">
  <% flash.each do |name, msg| %>
    <div id="gc-alert" class="gc-alert gc-alert-<%= name %>" role="alert">
      <button class="gc-close-button" onclick="closeAlert('gc-alert')" >
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="gc-alert-text" ><%= msg %></div>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav>
  <ul class="menu-items">
    <li>
      <%= link_to "Home", root_path, data: { item: 'Home' } %>
    </li>
    <li class="dropdown">
      <a href="#" data-item="Articles">Articles</a>
      <div class="dropdown-content">
        <%= link_to "List", articles_path, data: { item: 'List' } %> <br>
        <% if logged_in? %>
          <%= link_to "Create", new_article_path, data: { item: 'Create', 'turbo-method': :get } %> <br>
        <% end %>
      </div>
    </li>
    <li class="dropdown">
      <a href="#" data-item="Bloggers">Bloggers</a>
      <div class="dropdown-content">
        <%= link_to "List", users_path, data: { item: 'List' } %> <br>
        <% if logged_in? %>
          <%= link_to current_user.username, user_path(current_user) , data: { item: current_user.username } %> <br>
          <%= link_to "Logout", logout_path , data: { item: 'Logout', 'turbo-method': :delete } %> <br>
        <% else %>
          <%= link_to "Login", login_path, data: { item: 'Login' } %> <br>
          <%= link_to "Register", signup_path, data: { item: 'Register' } %> <br>
        <% end %>
      </div>
    </li>
    <li>
      <%= link_to "About", about_path, data: { item: 'About' } %> <br>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://unicons.iconscout.com/release/v4.0.0/css/line.css" %>
    <%= javascript_include_tag "main", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <footer>
      <div>
        <small>Copyright &copy;</small>
      </div>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>
<%= link_to "Go to home page", root_path %>

app/views/pages/home.html.erb
<div>
  <h1>Alpha Blog</h1>
  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr>
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <%= link_to "Sign up!", signup_path, class: "gc-button-link" %>
  <%= link_to "Articles listing", articles_path, class: "gc-button-link secondary" %>
  <%= link_to "About page", about_path, class: "gc-button-link secondary" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div id="gc-alert-error" class="gc-alert gc-alert-danger">
    <button class="gc-close-button" onclick="closeAlert('gc-alert-error')" >
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="gc-alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being <%= if obj.instance_of? User.class
                                                                                                                 "registered"
                                                                                                               else "saved"
                                                                                                               end%></h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true, class: 'gc-form') do |f| %>
  <p>
    <%= f.label :username, class: 'gc-form-label' %> <br>
    <%= f.text_field :username, class: 'gc-form-input', placeholder: 'Enter your new username', autocomplete: 'off' %>
  </p>
  <p>
    <%= f.label :email, class: 'gc-form-label' %> <br>
    <%= f.text_field :email, class: 'gc-form-input', placeholder: 'Enter your email', autocomplete: 'off' %>
  </p>
  <p>
    <%= f.label :password, class: 'gc-form-label' %> <br>
    <%= f.password_field :password, class: 'gc-form-input', placeholder: 'Enter your new password' %>
  </p>
  <p>
    <%= f.label :password_confirmation, class: 'gc-form-label' %> <br>
    <%= f.password_field :password_confirmation, class: 'gc-form-input', placeholder: 'Confirm your password' %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'gc-button gc-form-button') %>
  </p>
<% end %>

<br>

app/views/users/edit.html.erb
<div class="title">
  <h1>Edit your profile</h1>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="title">
  <h1>Alpha Bloggers</h1>
</div>

<% @users.each do |user| %>
  <div class="user-card-container">
    <div class="user-card">
      <h3 class="user-card-username">
        <%= link_to user.username, user_path(user), class: "" %>
      </h3>
      <div class="user-card-profile-picture">
        <%= gravatar_for user, size: 150, class: "profile-image" %>
      </div>
      <div class="user-card-articles-number">
        <%= pluralize user.articles.count, "article" %>
      </div>
      <div class="user-card-actions gc-button-group">
        <%= button_to "View profile", { action: "show", id: user.id }, { method: :get, class: 'gc-button' } %>
        <% if logged_in? && (user == current_user || current_user.admin? ) %>
          <%= button_to "Edit profile", { action: "edit", id: user.id }, { method: :get, class: 'gc-button secondary' } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<%= will_paginate @users %>

app/views/users/new.html.erb
<div class="title">
  <h1>Register</h1>
</div>

<%= render 'form' %>

<div>+´
  <%= link_to "Cancel and get back to listing", articles_path %>
</div>

app/views/users/show.html.erb
<h1 class="profile-username"><%= @user.username %></h1>
<h2 class="profile-username-role"><%= "[ADMIN]" if current_user.admin? %></h2>

<%= gravatar_for @user, size: 200, class: 'profile-image' %>

<% if logged_in? && (@user == current_user || current_user.admin? ) %>
  <div class="gc-button-group">
    <%= button_to "Edit profile", edit_user_path(@user), { method: :get, class: 'gc-button' } %>
    <%= button_to "Delete", user_path(@user), { method: :delete, class: 'gc-button secondary' } %>
  </div>
<% end %>

<h3 class="profile-username">Articles</h3>

<%= render 'articles/article', article: @user.articles %>

<%= will_paginate @articles %>